development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pcr_development
  pool: 5
  username: furuyayuuki
  password: Yuki0321
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pcr_test
  pool: 5
  username: furuyayuuki
  password: Yuki0321
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pcr_production
  pool: 5
  username: furuyayuuki
  password: Yuki0321
  host: localhost
  socket: /var/run/mysqld/mysqld.sock